apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: YOUR_ACCOUNT_ID.dkr.ecr.eu-central-1.amazonaws.com/nodeserver
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 3000 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: webapp
  type: LoadBalancer
